# Generated by Django 6.0.4 on 2026-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактний телефон')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
